#!/bin/bash

GRN=$'\e[1;32m'
YEL=$'\e[1;33m'
END=$'\e[0m'

clear
printf "${YEL}Adding Docker repository...\n\n${END}"

curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
echo 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable' > /etc/apt/sources.list.d/docker.list
apt-get update

clear
printf "${YEL}Docker is installing... \nDepending on your Internet, this may take a while.\n\n${END}"

echo y | apt-get install docker-ce
service docker start

clear
printf "${GRN}Docker successfully installed.\n"
printf "${YEL}Now download and install the Damn Vulnerable Web Application(DVWA)...\n\n${END}"

docker pull vulnerables/web-dvwa
docker run --rm -it -d -p 80:80 vulnerables/web-dvwa

cat << EOF > rundvwa
#!/bin/bash

docker run --rm -it -d -p 80:80 vulnerables/web-dvwa
ID=\$(docker ps | sed -n '2p' | cut -c 1-3)

docker exec -it \$ID /bin/bash -c 'sed -i s/"allow_url_include = Off"/"allow_url_include = On"/ /etc/php/7.0/apache2/php.ini'
docker exec -it \$ID /bin/bash -c 'service apache2 start' 

unset ID
EOF

chmod 755 rundvwa

clear
printf "${YEL}One last step...\n${END}"
ID=$(docker ps | sed -n '2p' | cut -c 1-3)

docker exec -it $ID /bin/bash -c 'sed -i s/"allow_url_include = Off"/"allow_url_include = On"/ /etc/php/7.0/apache2/php.ini'
docker exec -it $ID /bin/bash -c 'service apache2 start' 

unset ID
printf "\n\nYou can practice by heading to ${GRN}172.17.0.2${END} now.\n"
printf "User name is: ${YEL}admin${END}\n"
printf "Password is: ${YEL}password${END}"
printf "Make sure you click the ${YEL}Create\/Reset Databse${END} button before use."



