#!/bin/bash

GRN=$'\e[1;32m'
YEL=$'\e[1;33m'
END=$'\e[0m'

clear
printf "${YEL}Adding Docker repository...\n\n${END}"

curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
echo 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable' > /etc/apt/sources.list.d/docker.list
apt-get update

clear
printf "${YEL}Docker is installing... Depending on your Internet, this may take a while.\n\n${END}"

echo y | apt-get install docker-ce
service docker start

clear
printf "${GRN}Docker successfully installed.\n"
printf "${YEL}Now download and install the Damn Vulnerable Web Application(DVWA)...\n\n${END}"

docker pull vulnerables/web-dvwa
docker run --rm -it -d -p 80:80 vulnerables/web-dvwa

clear
printf "${YEL}One last step...\n${YEL}"
ID=$(docker ps | sed -n '2p' | cut -c 1-3)

docker exec -it $ID /bin/bash -c 'sed -i s/"allow_url_include = Off"/"allow_url_include = On"/ /etc/php/7.0/apache2/php.ini'
docker exec -it $ID /bin/bash -c 'service apache2 start' 

unset ID

cat << EOF > enableurl
#!/bin/bash

ID=\$(docker ps | sed -n '2p' | cut -c 1-3)

docker exec -it \$ID /bin/bash -c 'sed -i s/"allow_url_include = Off"/"allow_url_include = On"/ /etc/php/7.0/apache2/php.ini'
docker exec -it \$ID /bin/bash -c 'service apache2 start' 

unset ID
chmod 755 enableurl
EOF
