#!/bin/bash
clear
echo "adding Docker repository...\n\n"

curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
echo 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable' > /etc/apt/sources.list.d/docker.list
apt-get update

clear
echo "Docker is installing... Depending on your Internet, this may take a while.\n\n"

echo y | apt-get install docker-ce
service docker start

clear
echo "Docker successfully installed. Now download and install the Damn Vulnerable Web Application(DVWA)...\n\n"

docker pull vulnerables/web-dvwa
docker run --rm -it -d -p 80:80 vulnerables/web-dvwa

clear
echo "One last step..."
ID=$(docker ps | sed -n '2p' | cut -c 1-3)

docker exec -it $ID /bin/bash -c 'sed -i s/"allow_url_include = Off"/"allow_url_include = On"/ /etc/php/7.0/apache2/php.ini'
docker exec -it $ID /bin/bash -c 'service apache2 start' 

ID=""

cat << EOF > enableurl
#!/bin/bash

ID=$(docker ps | sed -n '2p' | cut -c 1-3)

docker exec -it $ID /bin/bash -c 'sed -i s/"allow_url_include = Off"/"allow_url_include = On"/ /etc/php/7.0/apache2/php.ini'
docker exec -it $ID /bin/bash -c 'service apache2 start' 

ID=""
EOF
